### ISSUE TITLE
shfmt not installed

### ISSUE THREAD

**Issue by mizlan** [HereIsKevin/neat#1]
Hi Kevin, it's Michael from IHS! You've done a lot of cool stuff here and in your other repositories. In your build pipeline you run a formatter `shfmt` which is not installed on systems by default:

https://github.com/HereIsKevin/neat/blob/b241af41642413f12808556b18513e0f84a46823/tool.sh#L5-L7

It would make sense for this only to be ran in a dev build and not release, so there could possibly be a flag for that.

**Comment by HereIsKevin** [comment]
Hi Michael! I just removed `shfmt` from the build pipeline with commit ec1bbcca712199a3dd07ad5a950991ab7485eee2. I've actually been meaning to do this for quite a while, as some version of `shfmt` from not that long ago had a major memory leak and infinite loop in its parser.

**Comment by HereIsKevin** [comment]
Off-topic side note: It seems like you really like using Clojure. My favorite programming language is TypeScript.
